### ISSUE TITLE
可以提供容器版本持久化存储的使用说明么

### ISSUE THREAD

**Issue by RickSKy** [saoxia/erpnext_china#1]

**Comment by saoxia** [comment]
最近比较忙，元旦过后更新一下

**Comment by saoxia** [comment]
先安装mariadb的独立docker
‘docker run -d --name db  \
	-p3306:3306    \
	-v /home/ebc/mariadb_data:/var/lib/mysql \
	--env MARIADB_ROOT_PASSWORD=数据库密码   \
	mariadb:11.2.3
docker exec -it db sh -c 'echo "[mysqld]" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "character-set-client-handshake = FALSE" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "collation-server = utf8mb4_unicode_ci" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "log-bin=mysql-bin" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "binlog_format = ROW" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "[mysql]" >> /etc/mysql/my.cnf'
docker exec -it db sh -c 'echo "default-character-set = utf8mb4" >> /etc/mysql/my.cnf'
docker restart db’

# 启动docker，项目初始化
docker run -it --network=host --name ebc  digitwise/erpnext_china_mdm

bench new-site \
	--db-host=127.0.0.1 --db-port=3306  \
	--db-name=ebc \
	--db-password=数据库密码  \
	--admin-password=frappe密码  \
	--db-root-password=数据库密码 \
	你的host域名
bench --site ebc.zhushigroup.cn install-app  erpnext erpnext_china erpnext_china_mdm
sudo service nginx restart
sudo service ssh restart
#注意，需要你自己在docker内配置nginx。在宿主机（不是docker内部）配置host
