### ISSUE TITLE
初学者，没搞懂怎么安装

### ISSUE THREAD

**Issue by ysbddlw** [saoxia/erpnext_china#3]
saoxia作者您好！我运行容器后进入按页面运行提示了错误。

WARN  Cannot connect to redis_cache to update assets_json
 WARN  Cannot connect to redis_cache to update assets_json
 WARN  Cannot connect to redis_cache to update assets_json
Done in 1.40s.
Compiling translations for erpnext_china
$ supervisorctl restart frappe:
unix:///var/run/supervisor.sock no such file
WARN: restarting supervisor group `frappe:` failed. Use `bench restart` to retry.
$ bench --site demo.com install-app erpnext erpnext_china
Site demo.com does not exist!

**Comment by saoxia** [comment]
建议按照官方文档的启动，先手动启动redis nginx mariadb，mariadb需要你自己拉个容器启动。
或者运行我的启动脚本，sh start.sh

**Comment by ysbddlw** [comment]
> 建议按照官方文档的启动，先手动启动redis nginx mariadb，mariadb需要你自己拉个容器启动。 或者运行我的启动脚本，sh start.sh

谢谢答复！我想问问数据库里面都是空的对吗？如果要使用就要全部按虚拟的企业重新开始设置一下？

**Comment by saoxia** [comment]
完毕
